[project]
name = "bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "livekit>=1.1.2",
    "livekit-api>=1.1.0",
    "scipy>=1.17.1",
    "websockets>=16.0"
]
